### ISSUE TITLE
Evaluation of phi nodes.

### ISSUE THREAD

**Issue by wks** [microvm/microvm-refimpl2#1]
Currently all instructions are evaluated sequentially, including PHI nodes. Theoretically all PHI nodes in the beginning of a particular basic block should be evaluated at the same time.

If a subsequent PHI node depends on a previous PHI node, the value of the previous PHI node is updated before the subsequent PHI node can get its old value. This causes error in some programs.

```
int swaps(int x, int y, int c) {
    for(int i=0; i<c; i++) {
        int tmp = x; x = y; y = tmp;
    }
    return x;
}
```

SSA form:

```
.funcdef .... (%x %y %c) {
  %entry:
    BRANCH %head
  %head:
    %x1 = PHI { %entry: %x; %body: %y1; }
    %y1 = PHI { %entry: %y; %body: %x1; }
    %i1 = PHI { %entry: @I64_0; %body: %i2; }
    %lt = SLT %i1 %c
    BRANCH2 %lt %body %exit
  %body:
    %i2 = ADD %i1 @I64_1;
    BRANCH %head
  %exit:
    RET %x1
}
```

Given arguments x=1, y=2, c=3. When entering head from entry, `%x1 = 1, %y1 = 2`. When branching back from body to head, the value of `%x1` and `%y1` should be swapped. However, the current implementation evaluates the PHI nodes one at a time.

```
// %body -> %head
%x1 = %y1 = 2
%y1 = %x1 = 2 // should be the old %x1, which was 1
```

The semantic of the Mu virtual machine itself should also be made clearer accordingly.

**Comment by hosking** [comment]
This doesn't make much sense. Phi nodes are ordered and evaluated in that order. In fact I would argue that the phi nodes in your example are malformed. A phi can take as arguments only SSA variables from the predecessor blocks. Your phis in this example have a circular dependency.

**Comment by eliotmoss** [comment]
Tony, I think when you have a variable updated in a loop, you can
have a cyclic dependency _on that path_.  This does not happen on
entering the loop.

Kunshan, this is another reason to redo the whole PHI thing by
making control transfers indicate the value they are giving to
each of the PHI variables.  I know they are theoretically
equivalent, but in the goto-with-values model you can easily
get hold of all the values first, then assign each value to
the proper PHI target.

Cheers -- Eliot

**Comment by eliotmoss** [comment]
I should have said: When you have situations like these swaps,
you can get a cycle of relationships between the old and new values.
Thus you have to do the assignment in two stages (gather all values,
assign all values), or else pre-analyze and arrange to use a temp to
break each cycle so as to do an assignment at a time and save the
assigning of _all_ values to temps.

This same kind of thing comes up in code generation when the
assignments of values to registers differs at a block boundary,
and the values thus need to be shuffled.

Regards -- Eliot

**Comment by hosking** [comment]
Right, my point being that the phis are evaluated in program order just like the other instructions.  There is no simultaneous evaluation of all phis in a block header.

**Comment by eliotmoss** [comment]
On 6/5/2015 9:55 AM, Antony Hosking wrote:

> Right, my point being that the phis are evaluated in program order just like the other instructions.
> There is no simultaneous evaluation of all phis in a block header.

... but there ought to be.  (Or else in the cyclic case we need to require adding suitable temps
to break the cycles and allow the PHIs to be executed sequentially ...  In other words, should
be push this onto the client?)

Best -- E

**Comment by hosking** [comment]
I assumed that clients would generate appropriate temporaries and order phis accordingly.  This is the way it is in llvm, and we have no reason to diverge from them do we?

**Comment by eliotmoss** [comment]
On 6/5/2015 10:03 AM, Antony Hosking wrote:

> I assumed that clients would generate appropriate temporaries and order phis accordingly. This is
> the way it is in llvm, and we have no reason to diverge from them do we?

I suppose not ... but the notion of executable PHI nodes seems weird to me :-) ... E

**Comment by wks** [comment]
I think here is the problem. SSA does not have the notion of
"temporaries": There is no `%tmp = %x`, but `%tmp = add %x, 0` is
okay, but has different meanings. The CFG I showed was generated by
converting "tmp = x; x = y; y = tmp" into the SSA form.

BTW, LLVM will (with -O1 flag) generate similar SSA form in which two
PHI nodes depends on each other, and is even simpler -- it has only
one loop header basic block and its last instruction branches to
itself:

```
define i32 @swaps(i32 %x, i32 %y, i32 %c) #0 {
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.cond, %entry
  %y.addr.0 = phi i32 [ %y, %entry ], [ %x.addr.0, %for.cond ]
  %i.0 = phi i32 [ 0, %entry ], [ %inc, %for.cond ]
  %x.addr.0 = phi i32 [ %x, %entry ], [ %y.addr.0, %for.cond ]
  %cmp = icmp slt i32 %i.0, %c
  %inc = add nuw nsw i32 %i.0, 1
  br i1 %cmp, label %for.cond, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  %x.addr.0.lcssa = phi i32 [ %x.addr.0, %for.cond ]
  ret i32 %x.addr.0.lcssa
}

```

2015-06-06 0:03 GMT+10:00 Antony Hosking notifications@github.com:

> I assumed that clients would generate appropriate temporaries and order phis
> accordingly. This is the way it is in llvm, and we have no reason to diverge
> from them do we?
> 
> Sent from my iPhone
>

**Comment by eliotmoss** [comment]
On 6/5/2015 10:45 AM, Kunshan Wang wrote:

> I think here is the problem. SSA does not have the notion of
> "temporaries": There is no `%tmp = %x`, but `%tmp = add %x, 0` is
> okay, but has different meanings. The CFG I showed was generated by
> converting "tmp = x; x = y; y = tmp" into the SSA form.

So:

1) It seems that LLVM does not directly solve this problem, but
    assumes that the PHI nodes are logically executed as a single
    parallel assignment.

2) When I was speaking of "temporaries", I guess I meant another
    SSA value, introduced only to break the cycle and allow the
    PHI nodes to be executed one at a time -- not quite the usual
    notion of PHI node, but what would be convenient here.  It
    might confuse analysis unless they were prepared to see it ...

Best -- E

**Comment by hosking** [comment]
Ah, my apologies Kunshan.  I've read the LLVM specs more closely.

> On Jun 5, 2015, at 11:09 AM, Eliot Moss notifications@github.com wrote:
> 
> On 6/5/2015 10:45 AM, Kunshan Wang wrote:
> 
> > I think here is the problem. SSA does not have the notion of
> > "temporaries": There is no `%tmp = %x`, but `%tmp = add %x, 0` is
> > okay, but has different meanings. The CFG I showed was generated by
> > converting "tmp = x; x = y; y = tmp" into the SSA form.
> 
> So:
> 
> 1) It seems that LLVM does not directly solve this problem, but
> assumes that the PHI nodes are logically executed as a single
> parallel assignment.

Yes, this appears to be the case:

For the purposes of the SSA form, the use of each incoming value is deemed to occur on the edge from the corresponding predecessor block to the current block (but after any definition of an ‘invoke‘ instruction’s return value on the same edge).

At runtime, the ‘phi‘ instruction logically takes on the value specified by the pair corresponding to the predecessor basic block that executed just prior to the current block.

So, does this not solve your problem?

**Comment by wks** [comment]
Fixed in https://github.com/microvm/microvm-refimpl2/commit/9bcf64aa79e1c00537027f782377cca3a518abf5 by assigning all PHI nodes and LANDINGPAD instructions together on the edge to the current block.
